title: Janice Whitson
description:  Voice of Data — Clarity. Empathy. Understanding.

contact:
  title: "Let’s talk"
  email: "janice.whitson.1@outlook.com"
  linkedin: "https://www.linkedin.com/in/janice-whitson-aa2a632/"
